// Abdulrahman AI - البيانات
const categories = [
    {
        name: "مساعدات الذكاء الاصطناعي",
        icon: "fa-solid fa-robot",
        tools: [
            { name: "ChatGPT", desc: "كتابة – برمجة – بحث – شرح – أفكار.", url: "https://chat.openai.com", icon: "fa-brands fa-openai" },
            { name: "Claude", desc: "تحليل وكتابة نصوص طويلة.", url: "https://claude.ai", icon: "fa-solid fa-comment" },
            { name: "Gemini", desc: "مساعد ذكاء اصطناعي متعدد الوسائط.", url: "https://gemini.google.com", icon: "fa-brands fa-google" },
            { name: "Microsoft Copilot", desc: "مساعد محادثة ومعلومات.", url: "https://copilot.microsoft.com", icon: "fa-brands fa-microsoft" },
            { name: "Perplexity AI", desc: "محرك بحث يجيب مع مصادر.", url: "https://www.perplexity.ai", icon: "fa-solid fa-magnifying-glass" },
            { name: "Hugging Face", desc: "استضافة ونماذج AI مفتوحة المصدر.", url: "https://huggingface.co", icon: "fa-solid fa-face-smile" },
            { name: "Poe", desc: "منصة تفاعل مع نماذج AI متعددة.", url: "https://poe.com", icon: "fa-solid fa-comments" },
            { name: "DeepAI", desc: "واجهات برمجية AI مجانية.", url: "https://deepai.org", icon: "fa-solid fa-brain" },
            { name: "LLaMA", desc: "نموذج ذكاء اصطناعي مفتوح المصدر.", url: "https://ai.meta.com/llama", icon: "fa-brands fa-meta" },
            { name: "Qwen Chat", desc: "روبوت دردشة متقدم.", url: "https://chat.qwen.ai", icon: "fa-solid fa-comment-dots" },
            { name: "HuggingChat", desc: "دردشة مفتوحة المصدر.", url: "https://huggingface.co/chat", icon: "fa-solid fa-face-smile" },
            { name: "YouChat", desc: "محرك بحث مع دردشة.", url: "https://you.com", icon: "fa-solid fa-y" },
            { name: "Phind", desc: "محرك بحث للمبرمجين.", url: "https://www.phind.com", icon: "fa-solid fa-code" },
            { name: "Forefront AI", desc: "منصة نماذج ذكاء اصطناعي متعددة.", url: "https://forefront.ai", icon: "fa-solid fa-star" },
            { name: "Janitor AI", desc: "إنشاء روبوتات دردشة AI قابلة للتخصيص.", url: "https://janitorai.com", icon: "fa-solid fa-robot" },
            { name: "Arena AI", desc: "بيئة تفاعلية لتجربة نماذج الذكاء الاصطناعي.", url: "https://arena.ai", icon: "fa-solid fa-gamepad" },
            { name: "Yupp AI", desc: "منصة متكاملة لأدوات الذكاء الاصطناعي.", url: "https://yupp.ai", icon: "fa-solid fa-brain" },
            { name: "Chatsonic", desc: "روبوت محادثة متقدم.", url: "https://writesonic.com/chatsonic", icon: "fa-solid fa-headphones" },
            { name: "Ora", desc: "تشغيل وتجربة نماذج الذكاء الاصطناعي.", url: "https://ora.ai", icon: "fa-solid fa-rocket" },
            { name: "Google Search Labs", desc: "تجارب أدوات AI من Google Labs.", url: "https://labs.google.com", icon: "fa-brands fa-google" },
            { name: "Noty AI", desc: "تدوين تلقائي من الصوت.", url: "https://noty.ai", icon: "fa-solid fa-note-sticky" },
            { name: "Tinywow AI", desc: "تحويل وتحرير مستندات وPDF.", url: "https://tinywow.com", icon: "fa-solid fa-file-pdf" }
        ]
    },
    {
        name: "البرمجة والتطوير",
        icon: "fa-solid fa-code",
        tools: [
            { name: "GitHub Copilot", desc: "يكتب الكود تلقائياً.", url: "https://github.com/features/copilot", icon: "fa-brands fa-github" },
            { name: "Cursor", desc: "محرر أكواد بالذكاء الاصطناعي.", url: "https://cursor.sh", icon: "fa-solid fa-cursor" },
            { name: "Replit", desc: "برمجة مباشرة داخل المتصفح.", url: "https://replit.com", icon: "fa-solid fa-code" },
            { name: "Codeium", desc: "مساعد برمجي مجاني.", url: "https://codeium.com", icon: "fa-solid fa-bolt" },
            { name: "v0.dev", desc: "تصميم واجهات React تلقائيًا.", url: "https://v0.dev", icon: "fa-solid fa-layer-group" },
            { name: "Bolt.new", desc: "بناء مواقع وتطبيقات بسرعة.", url: "https://bolt.new", icon: "fa-solid fa-bolt" },
            { name: "Supabase", desc: "قواعد بيانات وتطبيقات مفتوحة المصدر.", url: "https://supabase.com", icon: "fa-solid fa-database" },
            { name: "Firebase", desc: "باك اند جاهز وخدمات خلفية.", url: "https://firebase.google.com", icon: "fa-brands fa-google" },
            { name: "Vercel", desc: "نشر المواقع والتطبيقات بسهولة.", url: "https://vercel.com", icon: "fa-solid fa-cloud-upload-alt" },
            { name: "GitLab", desc: "منصة تطوير مع AI.", url: "https://gitlab.com", icon: "fa-brands fa-gitlab" },
            { name: "LangChain", desc: "إطار عمل لتطبيقات LLM.", url: "https://langchain.com", icon: "fa-solid fa-link" },
            { name: "Netlify", desc: "استضافة مواقع مجانية ونشر تلقائي.", url: "https://www.netlify.com", icon: "fa-solid fa-globe" },
            { name: "Retool", desc: "بناء أدوات داخلية بسرعة.", url: "https://retool.com", icon: "fa-solid fa-toolbox" },
            { name: "Tldraw AI", desc: "رسم وتحويله إلى كود برمجي.", url: "https://tldraw.com", icon: "fa-solid fa-draw-polygon" },
            { name: "Cogram", desc: "مساعدة برمجية ذكية داخل IDE.", url: "https://www.cogram.com", icon: "fa-solid fa-code" },
            { name: "Bloop AI", desc: "مساعد تطوير برمجيات سريع.", url: "https://bloop.ai", icon: "fa-solid fa-code-branch" },
            { name: "Emergent.sh", desc: "يساعد المطورين في بناء البرامج.", url: "https://emergent.sh", icon: "fa-solid fa-code-branch" },
            { name: "Rork", desc: "إدارة وتنظيم المشاريع البرمجية.", url: "https://rork.com", icon: "fa-solid fa-diagram-project" }
        ]
    },
    {
        name: "إنشاء المواقع والتطبيقات",
        icon: "fa-solid fa-globe",
        tools: [
            { name: "Durable AI", desc: "إنشاء موقع كامل خلال أقل من دقيقة.", url: "https://durable.co", icon: "fa-solid fa-rocket" },
            { name: "Wix ADI", desc: "إنشاء موقع كامل تلقائياً.", url: "https://www.wix.com", icon: "fa-brands fa-wix" },
            { name: "WordPress AI", desc: "إنشاء وإدارة مواقع ومدونات.", url: "https://wordpress.com", icon: "fa-brands fa-wordpress" },
            { name: "Shopify Magic", desc: "إنشاء متجر إلكتروني.", url: "https://www.shopify.com", icon: "fa-brands fa-shopify" },
            { name: "Framer AI", desc: "تصميم مواقع تفاعلية.", url: "https://www.framer.com", icon: "fa-solid fa-framer" },
            { name: "Webflow AI", desc: "إنشاء مواقع احترافية متجاوبة.", url: "https://webflow.com", icon: "fa-brands fa-webflow" },
            { name: "Squarespace AI", desc: "تصميم مواقع احترافية.", url: "https://www.squarespace.com", icon: "fa-brands fa-squarespace" },
            { name: "Zyro AI", desc: "تصميم مواقع بسرعة.", url: "https://zyro.com", icon: "fa-solid fa-bolt" },
            { name: "Bookmark", desc: "إنشاء موقع بخطوات بسيطة.", url: "https://www.bookmark.com", icon: "fa-solid fa-bookmark" },
            { name: "Bubble", desc: "إنشاء مواقع وأنظمة كاملة.", url: "https://bubble.io", icon: "fa-solid fa-shapes" },
            { name: "Base44", desc: "إنشاء تطبيقات وأنظمة بسهولة.", url: "https://base44.com", icon: "fa-solid fa-layer-group" },
            { name: "Glide", desc: "تحويل Google Sheets إلى تطبيق كامل.", url: "https://www.glideapps.com", icon: "fa-brands fa-google" },
            { name: "Adalo", desc: "إنشاء تطبيقات موبايل بسهولة.", url: "https://www.adalo.com", icon: "fa-solid fa-mobile-alt" },
            { name: "Softr", desc: "بناء مواقع من Airtable بدون برمجة.", url: "https://www.softr.io", icon: "fa-solid fa-table" },
            { name: "Uizard", desc: "تحويل النص إلى واجهات رقمية.", url: "https://uizard.io", icon: "fa-solid fa-wand-magic-sparkles" },
            { name: "Rocket.new", desc: "إنشاء تطبيقات تلقائياً.", url: "https://www.rocket.new", icon: "fa-solid fa-rocket" }
        ]
    },
    {
        name: "إنشاء الصور والتصميم",
        icon: "fa-solid fa-image",
        tools: [
            { name: "Midjourney", desc: "توليد صور إبداعية.", url: "https://www.midjourney.com", icon: "fa-solid fa-image" },
            { name: "DALL·E", desc: "إنشاء الصور باستخدام الذكاء الاصطناعي.", url: "https://openai.com/dall-e-3", icon: "fa-brands fa-openai" },
            { name: "Stable Diffusion", desc: "نموذج مفتوح لتوليد الصور.", url: "https://stability.ai", icon: "fa-solid fa-dice-d6" },
            { name: "Adobe Firefly", desc: "توليد صور وفيديو.", url: "https://firefly.adobe.com", icon: "fa-brands fa-adobe" },
            { name: "Canva", desc: "تصميم باحترافية.", url: "https://www.canva.com", icon: "fa-brands fa-canva" },
            { name: "Leonardo AI", desc: "صور عالية الجودة وتخصيص.", url: "https://leonardo.ai", icon: "fa-solid fa-wand-magic-sparkles" },
            { name: "Ideogram", desc: "صور دقيقة مع نص داخل الصورة.", url: "https://ideogram.ai", icon: "fa-solid fa-a" },
            { name: "Playground AI", desc: "توليد وتعديل الصور.", url: "https://playgroundai.com", icon: "fa-solid fa-paint-roller" },
            { name: "Craiyon", desc: "توليد صور من النصوص.", url: "https://www.craiyon.com", icon: "fa-solid fa-palette" },
            { name: "NightCafe", desc: "توليد صور فنية وإبداعية.", url: "https://nightcafe.studio", icon: "fa-solid fa-moon" },
            { name: "Dream by Wombo", desc: "رسم إبداعي باستخدام الذكاء الاصطناعي.", url: "https://dream.ai", icon: "fa-solid fa-cloud-moon" },
            { name: "StarryAI", desc: "تصميم لوحات فنية ومؤثرات بصرية.", url: "https://starryai.com", icon: "fa-solid fa-star" },
            { name: "Artbreeder", desc: "مزج وتطوير صور.", url: "https://www.artbreeder.com", icon: "fa-solid fa-dna" },
            { name: "DreamUp", desc: "إنشاء صور.", url: "https://dreamup.com", icon: "fa-solid fa-cloud-moon" },
            { name: "Remove.bg", desc: "حذف خلفية الصور.", url: "https://www.remove.bg", icon: "fa-solid fa-person-rays" },
            { name: "PhotoRoom", desc: "إزالة خلفيات الصور.", url: "https://www.photoroom.com", icon: "fa-solid fa-crop-simple" },
            { name: "Cleanup Pictures", desc: "إزالة العناصر من الصور.", url: "https://cleanup.pictures", icon: "fa-solid fa-eraser" },
            { name: "Clipdrop", desc: "أدوات تحرير وقطع الصور.", url: "https://clipdrop.co", icon: "fa-solid fa-scissors" },
            { name: "Gigapixel AI", desc: "تكبير الصور دون فقدان الجودة.", url: "https://www.topazlabs.com/gigapixel-ai", icon: "fa-solid fa-magnifying-glass-plus" },
            { name: "VanceAI", desc: "تحسين وتكبير الصور.", url: "https://vanceai.com", icon: "fa-solid fa-image" },
            { name: "Adobe Photoshop AI", desc: "تحرير صور ذكي.", url: "https://www.adobe.com/products/photoshop.html", icon: "fa-brands fa-adobe" },
            { name: "Pixlr", desc: "تعديل الصور أونلاين.", url: "https://pixlr.com", icon: "fa-solid fa-crop" },
            { name: "Photopea", desc: "بديل فوتوشوب مجاني.", url: "https://www.photopea.com", icon: "fa-solid fa-layers" },
            { name: "Fotor AI", desc: "أدوات تحرير صور سهلة.", url: "https://www.fotor.com", icon: "fa-solid fa-camera-retro" },
            { name: "Deep Dream Generator", desc: "صور فنية بأسلوب حلمي.", url: "https://deepdreamgenerator.com", icon: "fa-solid fa-dream" },
            { name: "NVIDIA GauGAN", desc: "رسم المناظر الطبيعية.", url: "https://www.nvidia.com/en-us/studio/canvas/", icon: "fa-brands fa-nvidia" },
            { name: "AutoDraw", desc: "رسم تلقائي بالذكاء الاصطناعي.", url: "https://www.autodraw.com", icon: "fa-solid fa-draw-polygon" },
            { name: "Magician Design", desc: "تصميم سريع لعناصر الجرافيك.", url: "https://magician.design", icon: "fa-solid fa-wand-magic" },
            { name: "Looka", desc: "إنشاء الشعارات والهوية البصرية.", url: "https://looka.com", icon: "fa-solid fa-pen-ruler" },
            { name: "LogoAI", desc: "تصميم شعارات سريع.", url: "https://logoai.com", icon: "fa-solid fa-pen-nib" },
            { name: "Brandmark", desc: "مولد شعارات AI.", url: "https://brandmark.io", icon: "fa-solid fa-trademark" },
            { name: "Kittl", desc: "إنشاء وتصميم صور.", url: "https://kittl.com", icon: "fa-solid fa-palette" },
            { name: "Icons8 AI", desc: "توليد أيقونات ورسوم رقمية.", url: "https://icons8.com", icon: "fa-solid fa-icons" },
            { name: "Pixray", desc: "تحويل النص إلى صور.", url: "https://pixray.gob.io", icon: "fa-solid fa-camera" },
            { name: "Avatar AI", desc: "إنشاء صور رمزية مخصصة.", url: "https://avatarai.me", icon: "fa-solid fa-user-astronaut" },
            { name: "Colorize AI", desc: "تلوين الصور القديمة.", url: "https://colorize.cc", icon: "fa-solid fa-fill-drip" },
            { name: "Artflow AI", desc: "شخصيات ورسومات خيالية.", url: "https://artflow.ai", icon: "fa-solid fa-wand-magic-sparkles" },
            { name: "SketchAR", desc: "تعليم الرسم.", url: "https://sketchar.tech", icon: "fa-solid fa-pencil" },
            { name: "PaddleGAN", desc: "توليد صور ذكية.", url: "https://github.com/PaddlePaddle/PaddleGAN", icon: "fa-brands fa-github" },
            { name: "PaintsChainer", desc: "تحويل الرسومات إلى لوحات.", url: "https://paintschainer.preferred.tech", icon: "fa-solid fa-paint-brush" },
            { name: "DeepArt", desc: "تحويل الصور إلى لوحات فنية.", url: "https://deepart.io", icon: "fa-solid fa-palette" },
            { name: "Toongineer Cartoonizer", desc: "تحويل الصور إلى كرتون.", url: "https://www.toongineer.com", icon: "fa-solid fa-face-smile" },
            { name: "Freepik", desc: "أدوات تصميم AI.", url: "https://freepik.com", icon: "fa-solid fa-image" },
            { name: "Designs AI", desc: "أدوات تصميم وشعارات احترافية.", url: "https://designs.ai", icon: "fa-solid fa-wand-magic-sparkles" },
            { name: "Pollo AI", desc: "إنشاء صور وفيديو.", url: "https://pollo.ai", icon: "fa-solid fa-video" },
            { name: "Qwen (Image/Video)", desc: "مولد صور وفيديو.", url: "https://qwen.ai", icon: "fa-solid fa-wand-magic-sparkles" }
        ]
    },
    {
        name: "صناعة الفيديو",
        icon: "fa-solid fa-video",
        tools: [
            { name: "Sora", desc: "مولد فيديو نص إلى فيديو.", url: "https://openai.com/sora", icon: "fa-solid fa-video" },
            { name: "Runway", desc: "تعديل فيديو احترافي.", url: "https://runwayml.com", icon: "fa-solid fa-film" },
            { name: "HeyGen", desc: "مولد فيديو من النص.", url: "https://www.heygen.com", icon: "fa-solid fa-user-tie" },
            { name: "Synthesia", desc: "إنشاء فيديوهات بشخصيات افتراضية.", url: "https://www.synthesia.io", icon: "fa-solid fa-robot" },
            { name: "Pika Labs", desc: "توليد فيديو قصير من النص.", url: "https://pika.art", icon: "fa-solid fa-wand-magic-sparkles" },
            { name: "Kling AI", desc: "فيديو وصوت AI.", url: "https://klingai.com", icon: "fa-solid fa-video" },
            { name: "InVideo AI", desc: "إنشاء فيديوهات تسويقية.", url: "https://invideo.io", icon: "fa-solid fa-play" },
            { name: "Pictory", desc: "تحويل النص إلى فيديو.", url: "https://pictory.ai", icon: "fa-solid fa-file-video" },
            { name: "Lumen5", desc: "تحويل المقالات إلى فيديوهات.", url: "https://lumen5.com", icon: "fa-solid fa-images" },
            { name: "CapCut", desc: "مونتاج فيديو سهل وقوي.", url: "https://www.capcut.com", icon: "fa-solid fa-scissors" },
            { name: "Veed.io AI", desc: "تحسين الفيديوهات وإضافة ترجمات.", url: "https://www.veed.io", icon: "fa-solid fa-closed-captioning" },
            { name: "Descript", desc: "تحرير صوت وفيديو ونص.", url: "https://www.descript.com", icon: "fa-solid fa-waveform" },
            { name: "Wisecut", desc: "تحرير الفيديو وإزالة الصمت.", url: "https://www.wisecut.video", icon: "fa-solid fa-scissors" },
            { name: "OpusClip", desc: "تحويل الفيديو الطويل إلى مقاطع قصيرة.", url: "https://www.opus.pro", icon: "fa-solid fa-clips" },
            { name: "Faceless.video", desc: "إنشاء فيديوهات بدون وجه.", url: "https://faceless.video", icon: "fa-solid fa-mask" },
            { name: "Eightify", desc: "تلخيص الفيديوهات.", url: "https://eightify.app", icon: "fa-solid fa-clock" },
            { name: "Morph Studio", desc: "تعديل الفيديوهات الذكية.", url: "https://www.morphstudio.com", icon: "fa-solid fa-wand-magic-sparkles" },
            { name: "Rephrase.ai", desc: "إعادة صياغة الفيديوهات.", url: "https://rephrase.ai", icon: "fa-solid fa-rotate" },
            { name: "Elai.io", desc: "إنشاء فيديوهات تعليمية.", url: "https://elai.io", icon: "fa-solid fa-graduation-cap" },
            { name: "Video Maker", desc: "إنشاء فيديو من النصوص.", url: "https://designs.ai/video-maker", icon: "fa-solid fa-video" },
            { name: "AI Animation Generator", desc: "إنشاء أنيميشن.", url: "https://designs.ai/ai-animation-generator", icon: "fa-solid fa-film" },
            { name: "AI Motion Graphics", desc: "إنشاء موشن جرافيك.", url: "https://designs.ai", icon: "fa-solid fa-film" },
            { name: "AI Video Subtitle Maker", desc: "إضافة ترجمة للفيديو.", url: "https://designs.ai", icon: "fa-solid fa-closed-captioning" },
            { name: "AI Video Scene Generator", desc: "إنشاء مشاهد فيديو.", url: "https://designs.ai", icon: "fa-solid fa-film" },
            { name: "AI Video Template Maker", desc: "إنشاء قوالب فيديو.", url: "https://designs.ai", icon: "fa-solid fa-clapperboard" }
        ]
    },
    {
        name: "الصوت والموسيقى",
        icon: "fa-solid fa-microphone",
        tools: [
            { name: "ElevenLabs", desc: "أصوات واقعية بالذكاء الاصطناعي.", url: "https://elevenlabs.io", icon: "fa-solid fa-waveform" },
            { name: "Suno", desc: "إنشاء موسيقى بالذكاء الاصطناعي.", url: "https://suno.ai", icon: "fa-solid fa-music" },
            { name: "Murf", desc: "تسجيلات صوتية احترافية.", url: "https://murf.ai", icon: "fa-solid fa-waveform" },
            { name: "TTSMaker", desc: "تحويل النص إلى صوت.", url: "https://ttsmaker.com", icon: "fa-solid fa-comment-dots" },
            { name: "Play.ht", desc: "تحويل النصوص إلى بودكاست صوتي.", url: "https://play.ht", icon: "fa-solid fa-podcast" },
            { name: "Resemble AI", desc: "إنشاء أصوات مخصصة.", url: "https://www.resemble.ai", icon: "fa-solid fa-microphone-alt" },
            { name: "WellSaid Labs", desc: "أصوات احترافية.", url: "https://wellsaidlabs.com", icon: "fa-solid fa-comment" },
            { name: "Whisper", desc: "تحويل الصوت إلى نص.", url: "https://huggingface.co/spaces/openai/whisper", icon: "fa-solid fa-ear-listen" },
            { name: "Deepgram", desc: "تحويل صوت إلى نص.", url: "https://deepgram.com", icon: "fa-solid fa-hearing" },
            { name: "Lalal.ai", desc: "فصل الصوت عن الموسيقى.", url: "https://www.lalal.ai", icon: "fa-solid fa-music" },
            { name: "Voice.ai", desc: "تحويل الصوت.", url: "https://voice.ai", icon: "fa-solid fa-microphone-alt" },
            { name: "VoiceMod", desc: "تغيير الصوت والبث المباشر.", url: "https://www.voicemod.net", icon: "fa-solid fa-masks-theater" },
            { name: "Papercup", desc: "ترجمة صوت الفيديو.", url: "https://www.papercup.com", icon: "fa-solid fa-language" },
            { name: "15.ai", desc: "إنشاء أصوات شخصيات.", url: "https://15.ai", icon: "fa-solid fa-robot" },
            { name: "LUVVOICE", desc: "توليد أصوات من النص.", url: "https://luvvoice.com", icon: "fa-solid fa-heart" },
            { name: "AudioLab AI", desc: "مؤثرات صوت ذكية.", url: "https://audiolab.ai", icon: "fa-solid fa-headphones" },
            { name: "VocaliD", desc: "أصوات AI مخصصة.", url: "https://vocalid.ai", icon: "fa-solid fa-user" },
            { name: "Cleanvoice AI", desc: "إزالة الضوضاء.", url: "https://cleanvoice.ai", icon: "fa-solid fa-volume-xmark" },
            { name: "Synthesys AI", desc: "توليد فيديو وصوت.", url: "https://synthesys.io", icon: "fa-solid fa-headphones" },
            { name: "Altered Studio", desc: "تغيير الصوت.", url: "https://www.altered.ai", icon: "fa-solid fa-exchange-alt" },
            { name: "Audiio AI", desc: "موسيقى وتأثيرات صوتية.", url: "https://www.audiio.com", icon: "fa-solid fa-music" },
            { name: "Typecast AI", desc: "تحويل النصوص إلى أصوات.", url: "https://typecast.ai", icon: "fa-solid fa-comment" },
            { name: "EchoWave", desc: "محرّر صوت AI.", url: "https://echowave.ai", icon: "fa-solid fa-waveform" },
            { name: "Speechnotes", desc: "تحويل الصوت إلى نص.", url: "https://speechnotes.co", icon: "fa-solid fa-microphone" },
            { name: "Speech Maker", desc: "تحويل النص إلى صوت.", url: "https://designs.ai/speech-maker", icon: "fa-solid fa-microphone" },
            { name: "AI Voice Cloning", desc: "استنساخ الصوت.", url: "https://designs.ai", icon: "fa-solid fa-microphone-alt" },
            { name: "AI Voice Over", desc: "إنشاء تعليق صوتي.", url: "https://designs.ai", icon: "fa-solid fa-microphone" },
            { name: "AI Podcast Generator", desc: "إنشاء بودكاست.", url: "https://designs.ai", icon: "fa-solid fa-podcast" },
            { name: "AI Music Generator", desc: "توليد موسيقى.", url: "https://designs.ai", icon: "fa-solid fa-music" },
            { name: "AI Sound Effect Generator", desc: "إنشاء مؤثرات صوتية.", url: "https://designs.ai", icon: "fa-solid fa-waveform" },
            { name: "AI Audio", desc: "إنشاء أو تعديل الصوت.", url: "https://designs.ai", icon: "fa-solid fa-headphones" }
        ]
    },
    {
        name: "الكتابة والمحتوى",
        icon: "fa-solid fa-pen-fancy",
        tools: [
            { name: "Jasper", desc: "كتابة المحتوى التسويقي.", url: "https://www.jasper.ai", icon: "fa-solid fa-pen-nib" },
            { name: "Copy.ai", desc: "كتابة الإعلانات والإيميلات.", url: "https://www.copy.ai", icon: "fa-solid fa-copy" },
            { name: "Writesonic", desc: "كتابة محتوى SEO.", url: "https://writesonic.com", icon: "fa-solid fa-pencil" },
            { name: "Grammarly", desc: "تصحيح القواعد وتحسين الكتابة.", url: "https://www.grammarly.com", icon: "fa-solid fa-check-double" },
            { name: "Quillbot", desc: "إعادة صياغة النصوص.", url: "https://quillbot.com", icon: "fa-solid fa-pen" },
            { name: "Rytr", desc: "أداة نصوص ذكية.", url: "https://rytr.me", icon: "fa-solid fa-pen" },
            { name: "Wordtune", desc: "تحسين الأسلوب اللغوي.", url: "https://www.wordtune.com", icon: "fa-solid fa-spell-check" },
            { name: "Anyword", desc: "تنبؤ أداء النصوص الإعلانية.", url: "https://anyword.com", icon: "fa-solid fa-chart-line" },
            { name: "Sudowrite", desc: "كتابة إبداعية وروايات.", url: "https://www.sudowrite.com", icon: "fa-solid fa-feather-pointed" },
            { name: "HyperWrite", desc: "تحسين الكتابة.", url: "https://www.hyperwriteai.com", icon: "fa-solid fa-bolt" },
            { name: "AI Writer", desc: "إنشاء مقالات تلقائية.", url: "https://ai-writer.com", icon: "fa-solid fa-newspaper" },
            { name: "Simplified AI", desc: "محتوى تسويقي.", url: "https://simplified.com/ai-writer", icon: "fa-solid fa-hashtag" },
            { name: "Scalenut", desc: "تحسين المحتوى.", url: "https://www.scalenut.com", icon: "fa-solid fa-chart-line" },
            { name: "TextCortex", desc: "توليد نصوص متعددة اللغات.", url: "https://textcortex.com", icon: "fa-solid fa-language" },
            { name: "AISEO", desc: "محتوى محسن لمحركات البحث.", url: "https://aiseo.ai", icon: "fa-solid fa-magnifying-glass" },
            { name: "Outranking AI", desc: "تحسين SEO.", url: "https://www.outranking.io", icon: "fa-solid fa-ranking-star" },
            { name: "CopySmith", desc: "كتابة نصوص تسويقية.", url: "https://copysmith.ai", icon: "fa-solid fa-copy" },
            { name: "Copymatic", desc: "نصوص تسويقية.", url: "https://copymatic.ai", icon: "fa-solid fa-copy" },
            { name: "LongShot AI", desc: "كتابة مقالات طويلة.", url: "https://longshot.ai", icon: "fa-solid fa-file-lines" },
            { name: "Ink AI", desc: "كتابة محتوى طويل.", url: "https://inkforall.com", icon: "fa-solid fa-pen" },
            { name: "AnyStory", desc: "إنشاء قصص وروايات.", url: "https://anystory.app", icon: "fa-solid fa-book" },
            { name: "NovelAI", desc: "كتابة روايات.", url: "https://novelai.net", icon: "fa-solid fa-book-open" },
            { name: "ShortlyAI", desc: "كتابة محتوى إبداعي.", url: "https://www.shortlyai.com", icon: "fa-solid fa-feather-pointed" },
            { name: "AI Dungeon", desc: "إنشاء قصص تفاعلية.", url: "https://play.aidungeon.io", icon: "fa-solid fa-dragon" },
            { name: "DeepStory AI", desc: "تحويل الأفكار إلى قصص.", url: "https://www.deepstory.ai", icon: "fa-solid fa-film" },
            { name: "Writecream", desc: "رسائل بريد إلكتروني.", url: "https://www.writecream.com", icon: "fa-solid fa-envelope" },
            { name: "ContentBot", desc: "نصوص تسويقية.", url: "https://contentbot.ai", icon: "fa-solid fa-file-alt" },
            { name: "GrowthBar", desc: "محتوى SEO.", url: "https://www.growthbarseo.com", icon: "fa-solid fa-chart-simple" },
            { name: "NeuralText", desc: "كتابة مقالات.", url: "https://www.neuraltext.com", icon: "fa-solid fa-magnifying-glass" },
            { name: "Phrasee", desc: "نصوص بريد إلكتروني.", url: "https://phrasee.co", icon: "fa-solid fa-envelope" },
            { name: "Kafkai", desc: "توليد محتوى.", url: "https://kafkai.com", icon: "fa-solid fa-globe" },
            { name: "Snazzy AI", desc: "نصوص إبداعية.", url: "https://snazzy.ai", icon: "fa-solid fa-star" },
            { name: "Peppertype AI", desc: "نصوص تسويقية.", url: "https://www.peppertype.ai", icon: "fa-solid fa-pepper-hot" },
            { name: "Chatbase", desc: "روبوتات محادثة.", url: "https://www.chatbase.co", icon: "fa-solid fa-comments" },
            { name: "Bertha AI", desc: "مساعد كتابة.", url: "https://bertha.ai", icon: "fa-brands fa-wordpress" },
            { name: "CopyMonkey", desc: "وصف المنتجات.", url: "https://copymonkey.ai", icon: "fa-brands fa-amazon" },
            { name: "TextFixer", desc: "إعادة صياغة النصوص.", url: "https://www.textfixer.com", icon: "fa-solid fa-spell-check" },
            { name: "GenApe", desc: "أدوات محتوى وفيديو AI.", url: "https://genape.ai", icon: "fa-solid fa-film" },
            { name: "Phrasly", desc: "تحسين محتوى نصي.", url: "https://phrasly.ai", icon: "fa-solid fa-feather-pointed" },
            { name: "Snov Email Writer", desc: "كتابة رسائل بريد.", url: "https://snov.io/email-writer", icon: "fa-solid fa-envelope" },
            { name: "ZeroGPT", desc: "كشف المحتوى.", url: "https://zerogpt.com", icon: "fa-solid fa-magnifying-glass" },
            { name: "Google Notebook LM", desc: "تدوين ذكي.", url: "https://notebooklm.google.com", icon: "fa-brands fa-google" }
        ]
    },
    {
        name: "العروض التقديمية",
        icon: "fa-solid fa-presentation-screen",
        tools: [
            { name: "Gamma", desc: "إنشاء عروض تقديمية.", url: "https://gamma.app", icon: "fa-solid fa-chart-pie" },
            { name: "Tome", desc: "عروض تقديمية وقصص.", url: "https://tome.app", icon: "fa-solid fa-book-open" },
            { name: "Beautiful AI", desc: "تصميم عروض مبتكرة.", url: "https://www.beautiful.ai", icon: "fa-solid fa-wand-magic-sparkles" },
            { name: "Slides AI", desc: "توليد شرائح العرض.", url: "https://www.slidesai.io", icon: "fa-solid fa-rectangle-list" },
            { name: "Decktopus", desc: "توليد عروض تقديمية.", url: "https://www.decktopus.com", icon: "fa-solid fa-presentation" },
            { name: "Pitch", desc: "تصميم عروض احترافية.", url: "https://pitch.com", icon: "fa-solid fa-chart-line" },
            { name: "Canva Presentations", desc: "تصميم عروض.", url: "https://www.canva.com/presentations", icon: "fa-brands fa-canva" },
            { name: "Visme", desc: "تصميم عروض.", url: "https://www.visme.co", icon: "fa-solid fa-chart-pie" },
            { name: "Prezi", desc: "عروض تفاعلية.", url: "https://prezi.com", icon: "fa-solid fa-presentation" },
            { name: "Powtoon", desc: "عروض متحركة.", url: "https://www.powtoon.com", icon: "fa-solid fa-film" },
            { name: "Genially", desc: "عروض تفاعلية.", url: "https://genial.ly", icon: "fa-solid fa-hand-pointer" },
            { name: "Google Slides", desc: "إنشاء عروض مشتركة.", url: "https://slides.google.com", icon: "fa-brands fa-google" },
            { name: "Slidebean", desc: "عروض جاهزة.", url: "https://slidebean.com", icon: "fa-solid fa-seedling" },
            { name: "Zoho Show", desc: "عروض تقديمية.", url: "https://www.zoho.com/show", icon: "fa-solid fa-presentation" },
            { name: "Haiku Deck", desc: "عروض بسيطة.", url: "https://www.haikudeck.com", icon: "fa-solid fa-leaf" },
            { name: "Storydoc", desc: "عروض مبيعات.", url: "https://www.storydoc.com", icon: "fa-solid fa-file-contract" },
            { name: "Slidesgo", desc: "قوالب PowerPoint.", url: "https://slidesgo.com", icon: "fa-brands fa-google" },
            { name: "EssayGrader", desc: "تصحيح المقالات.", url: "https://essaygrader.ai", icon: "fa-solid fa-graduation-cap" },
            { name: "AI Presentation Maker", desc: "إنشاء عروض.", url: "https://designs.ai/ai-presentation-maker", icon: "fa-solid fa-chart-pie" },
            { name: "AI Infographic Maker", desc: "إنشاء إنفوجرافيك.", url: "https://designs.ai/ai-infographic-maker", icon: "fa-solid fa-chart-simple" }
        ]
    },
    {
        name: "التسويق الرقمي",
        icon: "fa-solid fa-bullhorn",
        tools: [
            { name: "AdCreative", desc: "إنشاء إعلانات وبنرات.", url: "https://www.adcreative.ai", icon: "fa-solid fa-rectangle-ad" },
            { name: "HubSpot", desc: "إدارة العملاء والتسويق.", url: "https://www.hubspot.com", icon: "fa-brands fa-hubspot" },
            { name: "Predis", desc: "إنشاء منشورات سوشيال ميديا.", url: "https://predis.ai", icon: "fa-solid fa-hashtag" },
            { name: "Ocoya", desc: "كتابة وجدولة المحتوى.", url: "https://www.ocoya.com", icon: "fa-solid fa-calendar-check" },
            { name: "Pencil", desc: "توليد أفكار إعلانات.", url: "https://pencil.so", icon: "fa-solid fa-pencil" },
            { name: "Clickable", desc: "إنشاء إعلانات رقمية.", url: "https://www.clickable.ai", icon: "fa-solid fa-mouse-pointer" },
            { name: "Creasquare", desc: "تصميم محتوى للحملات.", url: "https://creasquare.io", icon: "fa-solid fa-square" },
            { name: "Attio", desc: "نظام CRM.", url: "https://attio.com", icon: "fa-solid fa-users" },
            { name: "Apollo", desc: "البحث عن العملاء.", url: "https://www.apollo.io", icon: "fa-solid fa-magnifying-glass-location" },
            { name: "Madgicx", desc: "تحسين إعلانات فيسبوك.", url: "https://madgicx.com", icon: "fa-brands fa-facebook" },
            { name: "Smartly.io AI", desc: "إعلانات سوشال ميديا.", url: "https://www.smartly.io", icon: "fa-solid fa-bolt" },
            { name: "Lately AI", desc: "تحويل محتوى إلى منشورات.", url: "https://www.lately.ai", icon: "fa-solid fa-share-alt" },
            { name: "Marpipe", desc: "اختبار تصاميم الإعلانات.", url: "https://marpipe.com", icon: "fa-solid fa-flask" },
            { name: "Pattern89", desc: "توقع أداء الإعلانات.", url: "https://pattern89.com", icon: "fa-solid fa-chart-line" },
            { name: "Revealbot", desc: "إدارة الحملات.", url: "https://revealbot.com", icon: "fa-solid fa-robot" },
            { name: "Adzooma", desc: "تحليل الإعلانات.", url: "https://adzooma.com", icon: "fa-solid fa-magnifying-glass-chart" },
            { name: "Optmyzr", desc: "تحسين إعلانات Google.", url: "https://optmyzr.com", icon: "fa-brands fa-google" },
            { name: "Drift", desc: "روبوت محادثة.", url: "https://www.drift.com", icon: "fa-solid fa-comment-dots" },
            { name: "Zopto", desc: "أتمتة التسويق.", url: "https://zopto.com", icon: "fa-brands fa-linkedin" },
            { name: "LinkedIn Sales Navigator", desc: "إيجاد العملاء.", url: "https://www.linkedin.com/sales", icon: "fa-brands fa-linkedin" },
            { name: "Close CRM", desc: "إدارة علاقات العملاء.", url: "https://close.com", icon: "fa-solid fa-phone" },
            { name: "Pipedrive", desc: "تتبع الصفقات.", url: "https://www.pipedrive.com", icon: "fa-solid fa-chart-line" },
            { name: "Freshsales", desc: "تتبع العملاء.", url: "https://www.freshworks.com/freshsales", icon: "fa-solid fa-leaf" },
            { name: "Salesloft", desc: "تحسين عمليات البيع.", url: "https://www.salesloft.com", icon: "fa-solid fa-bolt" },
            { name: "Outreach", desc: "أتمتة التواصل.", url: "https://www.outreach.io", icon: "fa-solid fa-paper-plane" },
            { name: "Clari", desc: "توقع المبيعات.", url: "https://www.clari.com", icon: "fa-solid fa-chart-line" },
            { name: "Yesware", desc: "تتبع رسائل البريد.", url: "https://www.yesware.com", icon: "fa-solid fa-envelope-check" },
            { name: "Reply", desc: "رسائل مبيعات.", url: "https://reply.io", icon: "fa-solid fa-reply-all" },
            { name: "Leadfeeder", desc: "معرفة الزوار.", url: "https://www.leadfeeder.com", icon: "fa-solid fa-chart-pie" },
            { name: "Gong", desc: "تحليل المبيعات.", url: "https://www.gong.io", icon: "fa-solid fa-gong" },
            { name: "Segment Twilio", desc: "بيانات عملاء.", url: "https://segment.com", icon: "fa-solid fa-chart-pie" },
            { name: "Feedly", desc: "متابعة الأخبار.", url: "https://feedly.com", icon: "fa-solid fa-rss" },
            { name: "AI Ad Generator", desc: "إنشاء إعلانات.", url: "https://designs.ai", icon: "fa-solid fa-bullhorn" },
            { name: "AI Campaign Generator", desc: "إنشاء حملات.", url: "https://designs.ai", icon: "fa-solid fa-bullhorn" },
            { name: "AI Keyword Generator", desc: "توليد كلمات مفتاحية.", url: "https://designs.ai", icon: "fa-solid fa-key" },
            { name: "AI Hashtag Generator", desc: "إنشاء هاشتاقات.", url: "https://designs.ai", icon: "fa-solid fa-hashtag" },
            { name: "AI Marketing Strategy", desc: "اقتراح استراتيجية.", url: "https://designs.ai", icon: "fa-solid fa-chess-king" },
            { name: "AI Trend Analyzer", desc: "تحليل الترند.", url: "https://designs.ai", icon: "fa-solid fa-chart-line" },
            { name: "AI Audience Analyzer", desc: "تحليل الجمهور.", url: "https://designs.ai", icon: "fa-solid fa-chart-pie" }
        ]
    },
    {
        name: "إدارة السوشيال ميديا",
        icon: "fa-solid fa-hashtag",
        tools: [
            { name: "Buffer", desc: "جدولة المنشورات.", url: "https://buffer.com", icon: "fa-solid fa-layer-group" },
            { name: "Hootsuite", desc: "إدارة حسابات السوشيال.", url: "https://hootsuite.com", icon: "fa-brands fa-hootsuite" },
            { name: "Metricool", desc: "تحليل وجدولة المحتوى.", url: "https://metricool.com", icon: "fa-solid fa-chart-simple" },
            { name: "TweetHunter", desc: "تخطيط وتحليل تغريدات.", url: "https://tweethunter.io", icon: "fa-brands fa-x-twitter" },
            { name: "Typefully", desc: "كتابة وجدولة تغريدات.", url: "https://typefully.com", icon: "fa-brands fa-x-twitter" },
            { name: "SocialBee", desc: "نشر المحتوى.", url: "https://socialbee.io", icon: "fa-brands fa-pinterest" },
            { name: "Publer", desc: "جدولة وتحليل المنشورات.", url: "https://publer.io", icon: "fa-solid fa-share-nodes" },
            { name: "Later", desc: "جدولة الصور والفيديوهات.", url: "https://later.com", icon: "fa-solid fa-calendar" },
            { name: "ContentStudio", desc: "تتبع الترند.", url: "https://contentstudio.io", icon: "fa-solid fa-wand-magic-sparkles" },
            { name: "Loomly", desc: "إدارة وجدولة المحتوى.", url: "https://www.loomly.com", icon: "fa-solid fa-lightbulb" },
            { name: "Planable", desc: "معاينة البوستات.", url: "https://planable.io", icon: "fa-solid fa-eye" },
            { name: "Sprout Social", desc: "تحليل الجمهور.", url: "https://sproutsocial.com", icon: "fa-brands fa-sprout-social" },
            { name: "Zoho Social", desc: "إدارة منصات التواصل.", url: "https://www.zoho.com/social", icon: "fa-solid fa-chart-bar" },
            { name: "Sendible", desc: "أتمتة نشر المحتوى.", url: "https://www.sendible.com", icon: "fa-solid fa-share-alt" },
            { name: "Vista Social", desc: "إدارة السوشيال ميديا.", url: "https://www.vistasocial.com", icon: "fa-solid fa-globe" },
            { name: "Beacons", desc: "أدوات صُنّاع المحتوى.", url: "https://beacons.ai", icon: "fa-solid fa-star" },
            { name: "AI Social Post Generator", desc: "إنشاء منشورات.", url: "https://designs.ai", icon: "fa-solid fa-hashtag" },
            { name: "AI Content Calendar", desc: "جدول نشر.", url: "https://designs.ai", icon: "fa-solid fa-calendar-days" },
            { name: "AI Social Media Planner", desc: "تخطيط المحتوى.", url: "https://designs.ai", icon: "fa-solid fa-calendar-check" },
            { name: "AI Content Idea Generator", desc: "توليد أفكار.", url: "https://designs.ai", icon: "fa-solid fa-lightbulb" },
            { name: "AI Ad Performance Analyzer", desc: "تحليل الأداء.", url: "https://designs.ai", icon: "fa-solid fa-chart-bar" }
        ]
    },
    {
        name: "التسويق بالبريد",
        icon: "fa-solid fa-envelope",
        tools: [
            { name: "Mailchimp", desc: "إنشاء حملات بريدية.", url: "https://mailchimp.com", icon: "fa-brands fa-mailchimp" },
            { name: "ConvertKit", desc: "إنشاء قوائم بريدية.", url: "https://convertkit.com", icon: "fa-solid fa-bolt" },
            { name: "ActiveCampaign", desc: "أتمتة التسويق.", url: "https://www.activecampaign.com", icon: "fa-solid fa-bullhorn" },
            { name: "MailerLite", desc: "تصميم رسائل بريدية.", url: "https://www.mailerlite.com", icon: "fa-solid fa-feather" },
            { name: "GetResponse", desc: "تسويق بالبريد.", url: "https://www.getresponse.com", icon: "fa-solid fa-reply" },
            { name: "AWeber", desc: "قوالب بريدية.", url: "https://www.aweber.com", icon: "fa-solid fa-at" },
            { name: "Sendinblue", desc: "إدارة البريد.", url: "https://www.sendinblue.com", icon: "fa-solid fa-paper-plane" },
            { name: "Campaign Monitor", desc: "تحليلات الحملات.", url: "https://www.campaignmonitor.com", icon: "fa-solid fa-chart-line" },
            { name: "Moosend", desc: "حملات بريدية.", url: "https://moosend.com", icon: "fa-solid fa-envelope-open-text" },
            { name: "Klaviyo", desc: "للتجارة الإلكترونية.", url: "https://www.klaviyo.com", icon: "fa-solid fa-cart-shopping" },
            { name: "Drip", desc: "أتمتة المبيعات.", url: "https://www.drip.com", icon: "fa-solid fa-droplet" },
            { name: "Omnisend", desc: "رسائل تسويقية.", url: "https://www.omnisend.com", icon: "fa-solid fa-bullhorn" },
            { name: "Benchmark Email", desc: "حملات بريدية.", url: "https://www.benchmarkemail.com", icon: "fa-solid fa-check" },
            { name: "Mailjet", desc: "رسائل بريد احترافية.", url: "https://www.mailjet.com", icon: "fa-solid fa-paper-plane" },
            { name: "AI Email Template Maker", desc: "إنشاء قوالب بريد.", url: "https://designs.ai", icon: "fa-solid fa-envelope" }
        ]
    },
    {
        name: "إدارة المشاريع",
        icon: "fa-solid fa-list-check",
        tools: [
            { name: "Notion", desc: "تنظيم الملاحظات والمهام.", url: "https://www.notion.so", icon: "fa-brands fa-notion" },
            { name: "ClickUp", desc: "إدارة مشاريع.", url: "https://clickup.com", icon: "fa-solid fa-arrow-up-right-dots" },
            { name: "Asana", desc: "تنظيم المهام.", url: "https://asana.com", icon: "fa-brands fa-asana" },
            { name: "Monday", desc: "إدارة المشاريع.", url: "https://monday.com", icon: "fa-solid fa-table-columns" },
            { name: "Trello", desc: "إدارة المهام.", url: "https://trello.com", icon: "fa-brands fa-trello" },
            { name: "Airtable", desc: "جداول بيانات متقدمة.", url: "https://airtable.com", icon: "fa-solid fa-table" },
            { name: "Miro", desc: "لوحات عمل.", url: "https://miro.com", icon: "fa-brands fa-miro" },
            { name: "Taskade", desc: "إدارة المشاريع.", url: "https://www.taskade.com", icon: "fa-solid fa-list-check" },
            { name: "Coda", desc: "مستندات ذكية.", url: "https://coda.io", icon: "fa-solid fa-file-code" },
            { name: "Basecamp", desc: "تعاون الفرق.", url: "https://basecamp.com", icon: "fa-solid fa-campground" },
            { name: "Evernote", desc: "تدوين الملاحظات.", url: "https://evernote.com", icon: "fa-brands fa-evernote" },
            { name: "Todoist", desc: "تنظيم مهام.", url: "https://todoist.com", icon: "fa-solid fa-check-double" },
            { name: "Quire", desc: "تنظيم المهام.", url: "https://quire.io", icon: "fa-solid fa-quote-right" },
            { name: "Zenkit", desc: "إدارة البيانات.", url: "https://zenkit.com", icon: "fa-solid fa-kanban" },
            { name: "Fellow", desc: "متابعة المهام.", url: "https://fellow.app", icon: "fa-solid fa-users-viewfinder" }
        ]
    },
    {
        name: "الاجتماعات والتعاون",
        icon: "fa-solid fa-users",
        tools: [
            { name: "Zoom", desc: "اجتماعات فيديو.", url: "https://zoom.us", icon: "fa-brands fa-zoom" },
            { name: "Google Meet", desc: "اجتماعات فيديو.", url: "https://meet.google.com", icon: "fa-brands fa-google" },
            { name: "Microsoft Teams", desc: "تعاون الفرق.", url: "https://www.microsoft.com/microsoft-teams", icon: "fa-brands fa-microsoft" },
            { name: "Otter.ai", desc: "تسجيل الاجتماعات.", url: "https://otter.ai", icon: "fa-solid fa-headphones" },
            { name: "Fireflies.ai", desc: "تلخيص الاجتماعات.", url: "https://fireflies.ai", icon: "fa-solid fa-fire" },
            { name: "MeetGeek", desc: "تلخيص الاجتماعات.", url: "https://meetgeek.ai", icon: "fa-solid fa-robot" },
            { name: "Loom", desc: "تسجيل الشاشة.", url: "https://www.loom.com", icon: "fa-solid fa-video" },
            { name: "Krisp", desc: "إزالة الضوضاء.", url: "https://krisp.ai", icon: "fa-solid fa-volume-xmark" },
            { name: "tl;dv", desc: "تسجيل المكالمات.", url: "https://tldv.io", icon: "fa-solid fa-tv" },
            { name: "Mmhmm", desc: "عروض بالفيديو.", url: "https://www.mmhmm.app", icon: "fa-solid fa-camera" },
            { name: "Vowel", desc: "اجتماعات ذكية.", url: "https://www.vowel.com", icon: "fa-solid fa-microphone" },
            { name: "Tactiq", desc: "استخراج النقاط.", url: "https://tactiq.io", icon: "fa-solid fa-list-check" },
            { name: "Whereby", desc: "اجتماعات فيديو.", url: "https://whereby.com", icon: "fa-solid fa-video" },
            { name: "Around", desc: "مكالمات فيديو.", url: "https://www.around.co", icon: "fa-solid fa-circle-nodes" },
            { name: "Superwrapper", desc: "أداة متكاملة.", url: "https://superwrapper.ai", icon: "fa-solid fa-toolbox" }
        ]
    },
    {
        name: "الأتمتة",
        icon: "fa-solid fa-gears",
        tools: [
            { name: "Zapier", desc: "أتمتة المهام.", url: "https://zapier.com", icon: "fa-brands fa-zapier" },
            { name: "Make", desc: "سيناريوهات أتمتة.", url: "https://www.make.com", icon: "fa-solid fa-link" },
            { name: "n8n", desc: "أتمتة العمليات.", url: "https://n8n.io", icon: "fa-solid fa-network-wired" },
            { name: "IFTTT", desc: "ربط التطبيقات.", url: "https://ifttt.com", icon: "fa-solid fa-toggle-on" },
            { name: "Bardeen", desc: "أتمتة الروتين.", url: "https://www.bardeen.ai", icon: "fa-solid fa-bolt" },
            { name: "Merlin AI", desc: "مساعد إنتاجية.", url: "https://merlin.foyer.work", icon: "fa-solid fa-hat-wizard" },
            { name: "Mem.ai", desc: "تنظيم المعرفة.", url: "https://mem.ai", icon: "fa-solid fa-brain" },
            { name: "Motion AI", desc: "جدولة ذكية.", url: "https://www.usemotion.com", icon: "fa-solid fa-calendar-check" },
            { name: "Clockwise", desc: "إدارة الوقت.", url: "https://www.getclockwise.com", icon: "fa-solid fa-clock" },
            { name: "Timely AI", desc: "تتبع الوقت.", url: "https://timelyapp.com", icon: "fa-solid fa-stopwatch" },
            { name: "Magic AI", desc: "إجراءات تلقائية.", url: "https://magic.ai", icon: "fa-solid fa-wand-magic-sparkles" },
            { name: "Clara Labs", desc: "تنظيم اجتماعات.", url: "https://claralabs.com", icon: "fa-solid fa-calendar-days" },
            { name: "Scribe AI", desc: "توثيق الإجراءات.", url: "https://scribehow.com", icon: "fa-solid fa-list-ol" },
            { name: "Text Blaze", desc: "قوالب نصوص.", url: "https://blaze.today", icon: "fa-solid fa-bolt" },
            { name: "Akkio", desc: "تحليل البيانات.", url: "https://www.akkio.com", icon: "fa-solid fa-chart-bar" },
            { name: "Fathom AI", desc: "تلخيص المكالمات.", url: "https://fathom.video", icon: "fa-solid fa-phone" },
            { name: "ClickUp AI", desc: "تنظيم المهام.", url: "https://clickup.com", icon: "fa-solid fa-arrow-up-right-dots" },
            { name: "Automate.io", desc: "أتمتة التسويق.", url: "https://automate.io", icon: "fa-solid fa-cogs" },
            { name: "Tray.io", desc: "أتمتة للشركات.", url: "https://tray.io", icon: "fa-solid fa-box" },
            { name: "Parabola", desc: "معالجة البيانات.", url: "https://parabola.io", icon: "fa-solid fa-chart-line" },
            { name: "Boomi", desc: "تكامل البيانات.", url: "https://boomi.com", icon: "fa-solid fa-cloud" },
            { name: "Jotform", desc: "نماذج وسير عمل.", url: "https://jotform.com", icon: "fa-solid fa-wpforms" },
            { name: "Box AI", desc: "إدارة المحتوى.", url: "https://box.com", icon: "fa-solid fa-boxes-stacked" },
            { name: "Indy", desc: "إدارة أعمال.", url: "https://indy.com", icon: "fa-solid fa-briefcase" },
            { name: "Reclaim.ai", desc: "تنظيم المواعيد.", url: "https://reclaim.ai", icon: "fa-solid fa-calendar-check" },
            { name: "x.ai", desc: "تنظيم اجتماعات.", url: "https://x.ai", icon: "fa-solid fa-calendar-days" },
            { name: "Calendar AI Assistant", desc: "تنظيم الاجتماعات.", url: "https://calendar.ai", icon: "fa-solid fa-calendar-alt" },
            { name: "Workflow AI Tools", desc: "أتمتة.", url: "https://workflowai.com", icon: "fa-solid fa-diagram-project" },
            { name: "AI Meeting Assistant", desc: "تلخيص الاجتماعات.", url: "https://meetingassistant.ai", icon: "fa-solid fa-people-arrows" },
            { name: "ChatGPT for Google Sheets", desc: "تحليل البيانات.", url: "https://workspace.google.com/marketplace/app/chatgpt_for_google_sheets/", icon: "fa-brands fa-google" },
            { name: "Fireflies Meeting Bot", desc: "تسجيل الاجتماعات.", url: "https://fireflies.ai", icon: "fa-solid fa-fire" }
        ]
    },
    {
        name: "إضافات المتصفح",
        icon: "fa-solid fa-puzzle-piece",
        tools: [
            { name: "Hunter", desc: "البحث عن إيميلات.", url: "https://hunter.io", icon: "fa-solid fa-envelope" },
            { name: "Scribe", desc: "إنشاء شروحات.", url: "https://scribehow.com", icon: "fa-solid fa-list-ol" },
            { name: "Tango", desc: "توثيق خطوات العمل.", url: "https://www.tango.us", icon: "fa-solid fa-list-check" },
            { name: "Keywords Everywhere", desc: "تحليل الكلمات.", url: "https://keywordseverywhere.com", icon: "fa-solid fa-key" },
            { name: "Momentum", desc: "صفحة بداية.", url: "https://momentumdash.com", icon: "fa-solid fa-rocket" },
            { name: "Notion Web Clipper", desc: "حفظ الصفحات.", url: "https://www.notion.so/web-clipper", icon: "fa-brands fa-notion" },
            { name: "MightyText", desc: "رسائل من الكمبيوتر.", url: "https://mightytext.net", icon: "fa-solid fa-comment-sms" },
            { name: "SEOquake", desc: "تحليل صفحات الويب.", url: "https://www.seoquake.com", icon: "fa-solid fa-magnifying-glass-chart" },
            { name: "GMass", desc: "بريد جماعي.", url: "https://www.gmass.co", icon: "fa-solid fa-envelope-bulk" },
            { name: "Evernote Web Clipper", desc: "حفظ محتوى.", url: "https://evernote.com/webclipper", icon: "fa-brands fa-evernote" },
            { name: "WhatFont", desc: "معرفة الخطوط.", url: "https://whatfont.org", icon: "fa-solid fa-font" }
        ]
    },
    {
        name: "التعليم والحياة",
        icon: "fa-solid fa-graduation-cap",
        tools: [
            { name: "Duolingo", desc: "تعلم اللغات.", url: "https://www.duolingo.com", icon: "fa-brands fa-duolingo" },
            { name: "Elsa Speak", desc: "تعلم النطق.", url: "https://elsaspeak.com", icon: "fa-solid fa-ear-listen" },
            { name: "Khan Academy", desc: "تعليم مجاني.", url: "https://www.khanacademy.org", icon: "fa-solid fa-school" },
            { name: "Coursera", desc: "دورات جامعية.", url: "https://www.coursera.org", icon: "fa-solid fa-certificate" },
            { name: "Udemy", desc: "دورات تعليمية.", url: "https://www.udemy.com", icon: "fa-brands fa-udemy" },
            { name: "Skillshare", desc: "تعلم المهارات.", url: "https://www.skillshare.com", icon: "fa-brands fa-skillshare" },
            { name: "Quizlet", desc: "اختبارات.", url: "https://quizlet.com", icon: "fa-solid fa-clipboard-question" },
            { name: "Brilliant", desc: "تعلم الرياضيات.", url: "https://brilliant.org", icon: "fa-solid fa-lightbulb" },
            { name: "Babbel", desc: "تحسين المحادثة.", url: "https://www.babbel.com", icon: "fa-brands fa-babbel" },
            { name: "Busuu", desc: "تعلم اللغات.", url: "https://www.busuu.com", icon: "fa-brands fa-busuu" },
            { name: "Memrise", desc: "تعلم اللغات.", url: "https://www.memrise.com", icon: "fa-solid fa-brain" },
            { name: "Lingvist", desc: "تعلم اللغات.", url: "https://lingvist.com", icon: "fa-solid fa-language" },
            { name: "Preply", desc: "دروس خصوصية.", url: "https://preply.com", icon: "fa-solid fa-chalkboard-user" },
            { name: "WolframAlpha", desc: "محرك حسابات.", url: "https://www.wolframalpha.com", icon: "fa-brands fa-wolfram" },
            { name: "Photomath", desc: "حل الرياضيات.", url: "https://photomath.com", icon: "fa-solid fa-calculator" },
            { name: "Socratic", desc: "حل الواجبات.", url: "https://socratic.org", icon: "fa-solid fa-graduation-cap" },
            { name: "FutureLearn", desc: "دورات تعليمية.", url: "https://www.futurelearn.com", icon: "fa-solid fa-graduation-cap" },
            { name: "Replika", desc: "صديق افتراضي.", url: "https://replika.ai", icon: "fa-solid fa-robot" },
            { name: "Calm", desc: "التأمل.", url: "https://www.calm.com", icon: "fa-solid fa-spa" },
            { name: "Headspace", desc: "جلسات التأمل.", url: "https://www.headspace.com", icon: "fa-solid fa-brain" },
            { name: "MyFitnessPal", desc: "خطط غذائية.", url: "https://www.myfitnesspal.com", icon: "fa-solid fa-heart-pulse" },
            { name: "Yummly", desc: "وصفات طبخ.", url: "https://www.yummly.com", icon: "fa-solid fa-utensils" },
            { name: "Mealime", desc: "تخطيط الوجبات.", url: "https://www.mealime.com", icon: "fa-solid fa-bowl-food" },
            { name: "Fabulous", desc: "تحسين العادات.", url: "https://www.fabulous.co", icon: "fa-solid fa-star" },
            { name: "Coach.me", desc: "متابعة الأهداف.", url: "https://www.coach.me", icon: "fa-solid fa-bullseye" },
            { name: "Flo", desc: "متابعة الصحة.", url: "https://flo.health", icon: "fa-solid fa-heart" },
            { name: "Sleep Reset", desc: "تحسين النوم.", url: "https://www.sleepreset.com", icon: "fa-solid fa-bed" },
            { name: "Studocu", desc: "مراجعة.", url: "https://studocu.com", icon: "fa-solid fa-graduation-cap" },
            { name: "Recipe By AI", desc: "مولّد وصفات.", url: "https://recipebyai.com", icon: "fa-solid fa-utensils" },
            { name: "Dishgen", desc: "وصفات AI.", url: "https://dishgen.com", icon: "fa-solid fa-bowl-rice" },
            { name: "LearnWorlds", desc: "كورسات.", url: "https://learnworlds.com", icon: "fa-solid fa-chalkboard" },
            { name: "Flo Health", desc: "صحة.", url: "https://flo.health", icon: "fa-solid fa-heart-pulse" },
            { name: "Musixmatch", desc: "كلمات الأغاني.", url: "https://musixmatch.com", icon: "fa-solid fa-music" },
            { name: "AI Course Content Generator", desc: "إنشاء محتوى تعليمي.", url: "https://designs.ai", icon: "fa-solid fa-graduation-cap" },
            { name: "AI Ebook Generator", desc: "إنشاء كتب إلكترونية.", url: "https://designs.ai", icon: "fa-solid fa-book" }
        ]
    },
    {
        name: "أدوات متخصصة",
        icon: "fa-solid fa-toolbox",
        tools: [
            { name: "DeepL", desc: "ترجمة نصوص.", url: "https://www.deepl.com", icon: "fa-solid fa-language" },
            { name: "PromptBase", desc: "تبادل أوامر prompts.", url: "https://promptbase.com", icon: "fa-solid fa-store" },
            { name: "Legal Robot", desc: "مساعدة قانونية.", url: "https://www.legalrobot.com", icon: "fa-solid fa-gavel" },
            { name: "Juro AI", desc: "عقود ذكية.", url: "https://juro.com", icon: "fa-solid fa-file-signature" },
            { name: "Hemingway AI", desc: "تحسين الكتابة.", url: "https://hemingwayapp.com", icon: "fa-solid fa-pen" },
            { name: "Zenefits", desc: "الموارد البشرية.", url: "https://www.zenefits.com", icon: "fa-solid fa-users-cog" },
            { name: "Mint", desc: "تحليل مالي.", url: "https://www.mint.com", icon: "fa-solid fa-coins" },
            { name: "Darktrace", desc: "أمان ذكي.", url: "https://www.darktrace.com", icon: "fa-solid fa-shield-halved" },
            { name: "Ramp", desc: "إدارة المصاريف.", url: "https://ramp.com", icon: "fa-solid fa-credit-card" },
            { name: "Figma AI Plugins", desc: "تصميم UI/UX.", url: "https://www.figma.com", icon: "fa-brands fa-figma" },
            { name: "Reimagine Home", desc: "تصميم داخلي.", url: "https://reimaginehome.ai", icon: "fa-solid fa-home" },
            { name: "Interior AI", desc: "تصميم غرف.", url: "https://interiorai.com", icon: "fa-solid fa-couch" },
            { name: "Patterned AI", desc: "إنشاء أنماط.", url: "https://patterned.ai", icon: "fa-solid fa-shapes" }
        ]
    },
    {
        name: "تحليل وSEO",
        icon: "fa-solid fa-magnifying-glass-chart",
        tools: [
            { name: "SimilarWeb", desc: "تحليل المواقع.", url: "https://www.similarweb.com", icon: "fa-solid fa-chart-simple" },
            { name: "SEMrush Trends", desc: "تحليل السوق.", url: "https://www.semrush.com/trends", icon: "fa-solid fa-chart-line" },
            { name: "Ahrefs", desc: "الكلمات المفتاحية.", url: "https://ahrefs.com", icon: "fa-solid fa-key" },
            { name: "Google Trends", desc: "الكلمات الأكثر بحثًا.", url: "https://trends.google.com", icon: "fa-brands fa-google" },
            { name: "AnswerThePublic", desc: "الأسئلة الشائعة.", url: "https://answerthepublic.com", icon: "fa-solid fa-circle-question" },
            { name: "BuzzSumo", desc: "المحتوى الأكثر انتشارًا.", url: "https://buzzsumo.com", icon: "fa-solid fa-fire" },
            { name: "SpyFu", desc: "كلمات المنافسين.", url: "https://www.spyfu.com", icon: "fa-solid fa-eye" },
            { name: "Surfer SEO", desc: "تحسين SEO.", url: "https://surferseo.com", icon: "fa-solid fa-chart-line" },
            { name: "Seona AI", desc: "أدوات SEO.", url: "https://seona.ai", icon: "fa-solid fa-magnifying-glass" },
            { name: "VidIQ", desc: "تحسين يوتيوب.", url: "https://vidiq.com", icon: "fa-brands fa-youtube" },
            { name: "TubeBuddy", desc: "تحليل يوتيوب.", url: "https://www.tubebuddy.com", icon: "fa-brands fa-youtube" },
            { name: "Brandwatch", desc: "مراقبة السمعة.", url: "https://www.brandwatch.com", icon: "fa-solid fa-chart-line" },
            { name: "Mention", desc: "مراقبة.", url: "https://mention.com", icon: "fa-solid fa-at" },
            { name: "Quantcast", desc: "تحليل الجمهور.", url: "https://www.quantcast.com", icon: "fa-solid fa-chart-bar" },
            { name: "Tableau", desc: "تحليل البيانات.", url: "https://www.tableau.com", icon: "fa-solid fa-chart-column" },
            { name: "Looker Studio", desc: "تقارير.", url: "https://lookerstudio.google.com", icon: "fa-brands fa-google" },
            { name: "MarketMuse", desc: "تحليل المحتوى.", url: "https://www.marketmuse.com", icon: "fa-solid fa-brain" },
            { name: "Crayon", desc: "تتبع المنافسين.", url: "https://www.crayon.co", icon: "fa-solid fa-eye" }
        ]
    },
    {
        name: "وظائف وسير ذاتية",
        icon: "fa-solid fa-user-tie",
        tools: [
            { name: "Kickresume", desc: "السيرة الذاتية.", url: "https://kickresume.com", icon: "fa-solid fa-file-lines" },
            { name: "Teal", desc: "تحسين السيرة.", url: "https://www.tealhq.com", icon: "fa-solid fa-briefcase" },
            { name: "FlowCV", desc: "بناء سيرة ذاتية.", url: "https://flowcv.com", icon: "fa-solid fa-file-lines" },
            { name: "BeamJobs", desc: "سيرة ذاتية.", url: "https://beamjobs.com", icon: "fa-solid fa-file-lines" },
            { name: "BoomJobs", desc: "سيرة ذاتية AI.", url: "https://boomjobs.com", icon: "fa-solid fa-rocket" },
            { name: "AI Resume Builders", desc: "بناء السيرة.", url: "https://www.resumebuilder.com", icon: "fa-solid fa-file" },
            { name: "AI Resume Maker", desc: "تصميم سيرة.", url: "https://designs.ai", icon: "fa-solid fa-file-lines" }
        ]
    },
    {
        name: "أدوات Designs AI",
        icon: "fa-solid fa-wand-magic-sparkles",
        tools: [
            { name: "Image Maker", desc: "توليد الصور.", url: "https://designs.ai/image-maker", icon: "fa-solid fa-image" },
            { name: "Logo Maker", desc: "إنشاء شعارات.", url: "https://designs.ai/logo-maker", icon: "fa-solid fa-star" },
            { name: "Design Maker", desc: "تصاميم.", url: "https://designs.ai/design-maker", icon: "fa-solid fa-palette" },
            { name: "Face Swapper", desc: "تبديل الوجوه.", url: "https://designs.ai/face-swapper", icon: "fa-solid fa-face-smile" },
            { name: "AI Draw", desc: "تحويل الرسومات.", url: "https://designs.ai", icon: "fa-solid fa-pencil" },
            { name: "Image to Text", desc: "استخراج النص.", url: "https://designs.ai", icon: "fa-solid fa-font" },
            { name: "Color Matcher", desc: "ألوان متناسقة.", url: "https://designs.ai", icon: "fa-solid fa-palette" },
            { name: "Graphic Maker", desc: "رسومات SVG.", url: "https://designs.ai", icon: "fa-solid fa-shapes" },
            { name: "Font Pairer", desc: "تنسيق الخطوط.", url: "https://designs.ai", icon: "fa-solid fa-text-height" },
            { name: "AI Background Remover", desc: "حذف الخلفية.", url: "https://designs.ai", icon: "fa-solid fa-eraser" },
            { name: "AI Image Upscaler", desc: "رفع الجودة.", url: "https://designs.ai", icon: "fa-solid fa-magnifying-glass-plus" },
            { name: "AI Poster Generator", desc: "إنشاء بوسترات.", url: "https://designs.ai", icon: "fa-solid fa-image" },
            { name: "AI Banner Generator", desc: "إنشاء بانرات.", url: "https://designs.ai", icon: "fa-solid fa-rectangle-ad" },
            { name: "AI Thumbnail Maker", desc: "صور مصغرة.", url: "https://designs.ai/thumbnail-maker", icon: "fa-brands fa-youtube" },
            { name: "AI Brand Kit Generator", desc: "هوية بصرية.", url: "https://designs.ai", icon: "fa-solid fa-palette" },
            { name: "AI Color Palette Generator", desc: "لوحات ألوان.", url: "https://designs.ai", icon: "fa-solid fa-palette" },
            { name: "AI Typography Generator", desc: "تنسيق الخطوط.", url: "https://designs.ai", icon: "fa-solid fa-text-height" },
            { name: "AI Mockup Generator", desc: "موك أب.", url: "https://designs.ai", icon: "fa-solid fa-cube" },
            { name: "AI T-Shirt Design", desc: "تصميم قمصان.", url: "https://designs.ai", icon: "fa-solid fa-shirt" },
            { name: "AI Business Card", desc: "بطاقات أعمال.", url: "https://designs.ai/business-card-maker", icon: "fa-solid fa-id-card" },
            { name: "AI Flyer Generator", desc: "فلاير.", url: "https://designs.ai", icon: "fa-solid fa-file" },
            { name: "AI Invitation Maker", desc: "دعوات.", url: "https://designs.ai", icon: "fa-solid fa-envelope-open-text" },
            { name: "AI Album Cover", desc: "أغلفة ألبومات.", url: "https://designs.ai/album-cover-generator", icon: "fa-solid fa-compact-disc" },
            { name: "AI Book Cover", desc: "أغلفة كتب.", url: "https://designs.ai/book-cover-maker", icon: "fa-solid fa-book" },
            { name: "AI Avatar Generator", desc: "أفاتار.", url: "https://designs.ai/avatar-generator", icon: "fa-solid fa-user-astronaut" },
            { name: "AI Character Creator", desc: "شخصيات.", url: "https://designs.ai", icon: "fa-solid fa-user" },
            { name: "AI Cartoon Generator", desc: "كرتون.", url: "https://designs.ai/cartoon-generator", icon: "fa-solid fa-face-smile" },
            { name: "AI Sketch Generator", desc: "تحويل لرسم.", url: "https://designs.ai", icon: "fa-solid fa-pencil" },
            { name: "AI Art Generator", desc: "لوحات فنية.", url: "https://designs.ai/art-generator", icon: "fa-solid fa-palette" },
            { name: "AI Style Transfer", desc: "نقل النمط.", url: "https://designs.ai", icon: "fa-solid fa-paint-roller" },
            { name: "AI Photo Enhancer", desc: "تحسين الصور.", url: "https://designs.ai", icon: "fa-solid fa-image" },
            { name: "AI Object Remover", desc: "إزالة عناصر.", url: "https://designs.ai", icon: "fa-solid fa-eraser" },
            { name: "AI Image Expander", desc: "توسيع الصور.", url: "https://designs.ai", icon: "fa-solid fa-expand" },
            { name: "AI Image Cropper", desc: "قص الصور.", url: "https://designs.ai", icon: "fa-solid fa-crop" },
            { name: "AI Image Filter", desc: "فلاتر.", url: "https://designs.ai", icon: "fa-solid fa-filter" },
            { name: "AI Lighting Adjuster", desc: "تعديل الإضاءة.", url: "https://designs.ai", icon: "fa-solid fa-sun" },
            { name: "AI Color Correction", desc: "تصحيح الألوان.", url: "https://designs.ai", icon: "fa-solid fa-fill-drip" },
            { name: "AI HDR Generator", desc: "تحسين الصورة.", url: "https://designs.ai", icon: "fa-solid fa-image" },
            { name: "AI Photo Retouch", desc: "تعديل الصور.", url: "https://designs.ai", icon: "fa-solid fa-wand-magic-sparkles" },
            { name: "AI Portrait Enhancer", desc: "تحسين بورتريه.", url: "https://designs.ai", icon: "fa-solid fa-portrait" },
            { name: "AI Landscape Generator", desc: "صور طبيعة.", url: "https://designs.ai", icon: "fa-solid fa-mountain-sun" },
            { name: "AI Product Photo", desc: "صور منتجات.", url: "https://designs.ai/product-photo-generator", icon: "fa-solid fa-camera" },
            { name: "AI Background Generator", desc: "خلفيات.", url: "https://designs.ai/background-generator", icon: "fa-solid fa-wall-brick" },
            { name: "AI Texture Generator", desc: "خامات.", url: "https://designs.ai", icon: "fa-solid fa-border-all" },
            { name: "AI Pattern Generator", desc: "أنماط.", url: "https://designs.ai", icon: "fa-solid fa-shapes" },
            { name: "AI Icon Generator", desc: "أيقونات.", url: "https://designs.ai/icon-generator", icon: "fa-solid fa-icons" },
            { name: "AI Sticker Generator", desc: "ملصقات.", url: "https://designs.ai", icon: "fa-solid fa-sticky-note" },
            { name: "AI Logo Animation", desc: "تحريك الشعار.", url: "https://designs.ai", icon: "fa-solid fa-play" },
            { name: "AI Brand Guidelines", desc: "دليل العلامة.", url: "https://designs.ai", icon: "fa-solid fa-book" },
            { name: "AI GIF Generator", desc: "صور GIF.", url: "https://designs.ai/gif-generator", icon: "fa-solid fa-film" },
            { name: "AI Meme Generator", desc: "ميمات.", url: "https://designs.ai/meme-generator", icon: "fa-solid fa-face-grin-tears" }
        ]
    },
    {
        name: "مواقع جمع أدوات AI",
        icon: "fa-solid fa-compass",
        tools: [
            { name: "Futurepedia", desc: "دليل أدوات AI.", url: "https://www.futurepedia.io", icon: "fa-solid fa-compass" },
            { name: "There's An AI", desc: "البحث عن أدوات AI.", url: "https://theresanaiforthat.com", icon: "fa-solid fa-magnifying-glass" }
        ]
    }
];

const translations = {
    en: {
        mainTitle: "Abdulrahman AI",
        homeLink: "Home",
        searchPlaceholder: "Search for AI tools...",
        noResultsMsg: "No tools match your search. Try another keyword!",
        backLink: "Back to all categories",
        visitBtn: "Visit",
        sidebarTitle: "Smart Menu",
        statCategories: "Categories",
        statTools: "Tools",
        statFav: "Favorites",
        topToolsTitle: "Most Visited",
        favoritesTitle: "My Favorites",
        copyright: "© 2026 Abdulrahman Radwan. All Rights Reserved.",
        sortDefault: "Default",
        sortName: "By Name",
        sortCount: "By Count"
    },
    ar: {
        mainTitle: "Abdulrahman AI",
        homeLink: "الرئيسية",
        searchPlaceholder: "البحث عن أدوات الذكاء الاصطناعي...",
        noResultsMsg: "لا توجد أدوات تطابق بحثك. جرب كلمة أخرى!",
        backLink: "العودة إلى جميع الأقسام",
        visitBtn: "زيارة",
        sidebarTitle: "القائمة الذكية",
        statCategories: "الأقسام",
        statTools: "الأدوات",
        statFav: "المفضلة",
        topToolsTitle: "الأكثر زيارة",
        favoritesTitle: "مفضلتي",
        copyright: "© 2026 Abdulrahman Radwan. جميع الحقوق محفوظة.",
        sortDefault: "الافتراضي",
        sortName: "بالاسم",
        sortCount: "بالعدد"
    }
};

const typingTexts = [
    "500+ AI Tools in one place",
    "Design, Write & Video Editing",
    "Programming & Development",
    "Your Ultimate AI Tools Guide 2026"
];

const totalTools = categories.reduce((sum, cat) => sum + cat.tools.length, 0);
console.log(`Total tools: ${totalTools} in ${categories.length} categories`);
